---
- name: Ensure pm2 is installed
  npm:
    name: pm2
    global: yes
    version: latest
  notify: restart pm2

- name: Delete all apps
  command: >
    pm2 delete all
  ignore_errors: yes

- name: Start apps
  command: >
    pm2 start {{ item }}
  with_items: pm2_apps

- name: Install startup script
  command: >
    pm2 startup centos

